### PR TITLE
Fix characters-program

### LINKED ISSUE #15: Fix characters-program
- [x] Fix tests (userAccount -> characterAccount).
- [x] State and instructions modules' items should be exported by the lib.
- [x] Character old name must be zeroed before updating.
- [x] Add a prefix to the character's PDA seeds to avoid [collision attacks](https://en.wikipedia.org/wiki/Collision_attack#Chosen-prefix_collision_attack).

### PR DESCRIPTION
**Pull request by lucasig11**
Closes #15.

### CODE REVIEW

File: characters-program/programs/characters-program/src/state.rs [hunk 1]
```diff
@@ -14,34 +16,43 @@ pub struct CharacterAccount {
...
+        );
+        let mut new_name = [0u8; NAME_MAX_LENGTH];
+        new_name[..name.len()].copy_from_slice(name.as_ref());
+        self.name = new_name;
+        Ok(())
+    }
+
+    #[inline]
+    /// Increase character experience by `exp`.
+    pub fn set_exp(&mut self, exp: u64) {
```
Comment (eliagoris) [inline characters-program/programs/characters-program/src/state.rs:55]: I suggest changing the function name to `add_exp` since it's increasing the exp

```suggestion
    pub fn add_exp(&mut self, exp: u64) {
```

Comment (eliagoris) [reply characters-program/programs/characters-program/src/state.rs:55]: But we'll also need to decrease Character's exp. (i.e., when they die?)

Make sure you can decrease the exp in the same function if you send a negative number

File: characters-program/programs/characters-program/src/state.rs [hunk 2]
```diff
@@ -14,34 +16,43 @@ pub struct CharacterAccount {
...
-            require!(
-                name.len() <= NAME_MAX_LENGTH,
-                ErrorCode::MaxNameLengthExceeded
-            );
-            self.name[..name.len()].copy_from_slice(name.as_ref());
+            self.set_name(&name)?;
         }
 
-        self.exp += dto.exp.unwrap_or(0);
+        self.set_exp(dto.exp.unwrap_or(0));
```
Comment (eliagoris) [inline characters-program/programs/characters-program/src/state.rs:37]: I suggest changing the function name to `add_exp` since it's increasing the exp
```suggestion
        self.add_exp(dto.exp.unwrap_or(0));
```

File: characters-program/tests/characters-program.ts [hunk 3]
```diff
@@ -52,10 +52,10 @@ describe("characters-program", () => {
       .accounts({
         token: mintAddress,
         owner: characterOwner.publicKey,
-        authority: characterAuthority.publicKey,
+        authority: gameAuthority.publicKey,
```
Comment (eliagoris) [inline characters-program/tests/characters-program.ts:55]: Can send any authority? How do we make sure the authority is only a wallet we trust? (noob question)

File: characters-program/programs/characters-program/src/state.rs (hunk 1 above)
Comment (lucasig11) [reply characters-program/programs/characters-program/src/state.rs:55]: I was thinking: doesn't it make more sense to give less exp (or no exp at all), instead of decreasing it? Idk, I don't see experience as a status that one'd lose, different from attributes like honor, defense, attack, etc.

Comment (eliagoris) [reply characters-program/programs/characters-program/src/state.rs:55]: I think it's cool to die and lose experience, like a traditional RPG. Maybe we should even consider removing honor and working with only experience/level

Comment (lucasig11) [reply characters-program/programs/characters-program/src/state.rs:55]: All right! I'm working on that.

**Review by eliagoris — APPROVED** [review]
